spring:
  datasource:
    url: jdbc:mysql://localhost:3306/many_to_many_test?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl